// @vitest-environment node
//
// The aid is generated by CODE (design D2b) at the moment the agent writes a shared collection's
// schema — not invented by the model, and not deferred to the first deploy.
//
// Before this, the two steps disagreed: the agent wrote `app.json` and then created the app's
// first collection, and the acceptance gate refused it with "app.json declares no `aid` string".
// The only ways forward were to invent an aid (the thing the design generates it to prevent) or to
// deploy an app with no collections first, which nobody would think of.
import { describe, it, expect, beforeEach } from "vitest";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { declaresSharedStorage, withGeneratedAid, wroteSchema } from "../../../server/infra/collectionToolAid.js";
import { makeTempDir } from "../../support/tempDir";

const firestoreSchema = { title: "Bookings", primaryKey: "id", storage: { type: "firestore" }, fields: {} };
const localSchema = { title: "Notes", primaryKey: "id", dataPath: "data/notes/items", fields: {} };

let root = "";
const appJson = () => path.join(root, "app.json");
const aidOf = () => JSON.parse(readFileSync(appJson(), "utf-8")).aid;

/** A handler that records what reached it and answers differently on each call, so "was it
 *  retried, and with what?" is answerable. */
const spyHandler = (...answers: string[]) => {
  const calls: Record<string, unknown>[] = [];
  const handler = (args: Record<string, unknown>) => {
    calls.push(args);
    return Promise.resolve(answers[calls.length - 1] ?? answers[answers.length - 1] ?? "inner ran");
  };
  return { calls, handler };
};

describe("declaresSharedStorage", () => {
  it("is true only for a putSchema whose records live in the app", () => {
    expect(declaresSharedStorage({ action: "putSchema", schema: firestoreSchema })).toBe(true);
    expect(declaresSharedStorage({ action: "putSchema", schema: localSchema })).toBe(false);
    // A local collection's repository has no app.json to write to, and giving one to a folder that
    // happens to hold a stray file is a decision this tool has no business making.
    expect(declaresSharedStorage({ action: "getItems", schema: firestoreSchema })).toBe(false);
    expect(declaresSharedStorage({ action: "putSchema" })).toBe(false);
  });
});

describe("wroteSchema", () => {
  // The engine's success is JSON with `written: true`; every refusal is prose. Anything else means
  // the write did not happen, and a mint made for it has to go back.
  it("recognises the engine's success and nothing else", () => {
    expect(wroteSchema('{"collection":"responses","written":true}')).toBe(true);
    expect(wroteSchema('{"collection":"responses","written":false}')).toBe(false);
    expect(wroteSchema("unknown collection 'responses'")).toBe(false);
    expect(wroteSchema("")).toBe(false);
  });
});

describe("withGeneratedAid", () => {
  beforeEach(() => {
    root = makeTempDir("mt-tool-aid-");
  });

  it("mints the aid before the engine reads the declaration", async () => {
    writeFileSync(appJson(), JSON.stringify({ members: { "owner@example.com": { "*": "owner" } } }));
    const spy = spyHandler('{"written":true}');
    const message = await withGeneratedAid(spy.handler, () => root)({ action: "putSchema", schema: firestoreSchema });
    expect(message).toBe('{"written":true}');
    expect(aidOf()).toMatch(/^[0-9a-f]{8}-/);
    // One call, not a refusal-and-retry: the engine does not refuse this, it silently skips the
    // collection and reports success, so there is nothing to react to afterwards.
    expect(spy.calls).toHaveLength(1);
    expect(JSON.parse(readFileSync(appJson(), "utf-8")).members).toEqual({ "owner@example.com": { "*": "owner" } });
  });

  it("takes the aid back when the write did not happen", async () => {
    // A refused call must leave nothing behind. Minting first is what makes the write work at all,
    // so the cost is paid by reverting rather than by trying to predict the engine's answer.
    writeFileSync(appJson(), JSON.stringify({ members: {} }));
    const spy = spyHandler("unknown collection 'responses' — create it by writing SKILL.md + schema.json");
    const message = await withGeneratedAid(spy.handler, () => root)({ action: "putSchema", schema: firestoreSchema });
    expect(message).toContain("unknown collection");
    expect(JSON.parse(readFileSync(appJson(), "utf-8")).aid).toBeUndefined();
    // And nothing else about the file changed.
    expect(JSON.parse(readFileSync(appJson(), "utf-8")).members).toEqual({});
  });

  it("leaves an aid it did NOT mint alone when the write fails", async () => {
    writeFileSync(appJson(), JSON.stringify({ aid: "already-there", members: {} }));
    await withGeneratedAid(spyHandler("refused").handler, () => root)({ action: "putSchema", schema: firestoreSchema });
    expect(aidOf()).toBe("already-there");
  });

  it("says what to write when the folder is not a shared app at all", async () => {
    const spy = spyHandler('{"written":true}');
    const message = await withGeneratedAid(spy.handler, () => root)({ action: "putSchema", schema: firestoreSchema });
    // Refused BEFORE the engine: writing the schema would produce a collection nothing discovers,
    // and the engine would report that as a success.
    expect(spy.calls).toHaveLength(0);
    expect(message).toContain("app.json");
    expect(message).toContain("members");
  });

  it("takes the aid back when the write THREW rather than refused", async () => {
    // The route turns a thrown handler into "manageCollection failed", so it is a failed call like
    // any other — and it must not be the one path that keeps the mint.
    writeFileSync(appJson(), JSON.stringify({ members: {} }));
    const wrapped = withGeneratedAid(
      () => Promise.reject(new Error("disk went away")),
      () => root,
    );
    await expect(wrapped({ action: "putSchema", schema: firestoreSchema })).rejects.toThrow("disk went away");
    expect(JSON.parse(readFileSync(appJson(), "utf-8")).aid).toBeUndefined();
  });

  it("does not let a failing write take the aid a successful one is using", async () => {
    // Two shared schema writes racing in one repository both see a manifest with no aid. Without
    // the whole mint/write/rollback being one transaction, the loser's rollback removes the aid the
    // winner's collection is now backed by — a shared collection with no app identity, and nothing
    // to notice it by.
    writeFileSync(appJson(), JSON.stringify({ members: {} }));
    const wrapped = withGeneratedAid(
      async (args) => {
        // The refusal resolves LATER than the success, which is the interleaving that breaks it.
        await new Promise((resolve) => setTimeout(resolve, args.slug === "slow" ? 10 : 0));
        return args.slug === "slow" ? "refused: unknown collection" : '{"written":true}';
      },
      () => root,
    );

    const [ok, refused] = await Promise.all([
      wrapped({ action: "putSchema", slug: "fast", schema: firestoreSchema }),
      wrapped({ action: "putSchema", slug: "slow", schema: firestoreSchema }),
    ]);
    expect(ok).toBe('{"written":true}');
    expect(refused).toContain("refused");
    expect(aidOf()).toMatch(/^[0-9a-f]{8}-/);
  });

  it("does not touch a local collection's write", async () => {
    const spy = spyHandler('{"written":true}');
    await withGeneratedAid(spy.handler, () => root)({ action: "putSchema", schema: localSchema });
    expect(spy.calls).toHaveLength(1);
    expect(() => readFileSync(appJson(), "utf-8")).toThrow();
  });
});
