// Give `app.json` its `aid` when the engine says that is the ONE thing missing.
//
// The design (D2b) says the aid is generated by code when `app.json` is written — not invented by
// the model, and not deferred to publish. `ensureAid` does the generating, but it ran only inside
// `manageSharedApp`, which is a later step than the one that needs it: the acceptance gate refuses
// a firestore schema whose root declares no aid, so an agent writing `app.json` and then creating
// the app's first collection was told
//
//     …/app.json declares no `aid` string
//
// and had no way forward except to invent one — the exact thing the design generates it to
// prevent — or to deploy an app with no collections first, which is not a step anybody would
// think of.
//
// WHY BEFORE, AND WHY IT UNDOES ITSELF. Doing it afterwards, by reading the engine's refusal, was
// the first attempt and it does not work: `putSchema` does not refuse. It writes the file, logs
// "schema.json rejected after validation, skipping" to the server's stderr, and answers the agent
// `{"collection":"responses","written":true}` — a success, for a collection that discovery then
// skips. There is nothing in the reply to react to, and the agent has been told it is done.
//
// So the aid is minted first. What that costs — a UUID left in `app.json` after a call the engine
// rejects for some OTHER reason (an unknown slug, a schema that does not parse) — is paid back by
// undoing it: a mint that this call made is removed again unless the write actually succeeded. A
// refused tool call leaves nothing behind, which is the property that matters, and it is kept by
// reverting rather than by predicting.
import { isRecord } from "../../common/isRecord.js";
import { ensureAid } from "../backends/sharedApp/ensureAid.js";
import { manifestKey } from "../backends/sharedApp/manifestWrite.js";
import { updateManifest } from "../backends/sharedApp/manifestWrite.js";
import { serializeBy } from "../backends/sharedApp/serialize.js";

/** Does this payload write a schema whose records live in the app's Firestore?
 *
 *  Only those. A local collection's repository has no `app.json` to write to, and giving one to a
 *  folder that happens to hold a stray file is a decision this tool has no business making. */
export function declaresSharedStorage(args: Record<string, unknown>): boolean {
  if (args.action !== "putSchema" || !isRecord(args.schema)) return false;
  const storage = args.schema.storage;
  return isRecord(storage) && storage.type === "firestore";
}

/** Did the engine actually write the schema?
 *
 *  Its success is JSON carrying `written: true`; every refusal is prose. Anything that is not that
 *  success means the call did not happen, and a mint made for it has to go back. */
export function wroteSchema(narration: string): boolean {
  let parsed: unknown;
  try {
    parsed = JSON.parse(narration);
  } catch {
    return false;
  }
  return isRecord(parsed) && parsed.written === true;
}

/** Wrap a manageCollection handler so a shared collection's `app.json` has an `aid` before the
 *  engine reads it — and so a call that then fails leaves the declaration as it found it.
 *
 *  A failure is returned as prose rather than thrown: the agent's contract with this tool is text
 *  it can act on, and "there is no app.json here" is the most actionable thing this step can say. */
export function withGeneratedAid(handler: (args: Record<string, unknown>) => Promise<string>, rootOf: () => string) {
  return async (args: Record<string, unknown>): Promise<string> => {
    if (!declaresSharedStorage(args)) return handler(args);
    const root = rootOf();
    // MINT, WRITE and ROLLBACK are one transaction, and each step being atomic on its own is not
    // enough. Two shared schema writes racing in one repository both see a manifest with no aid;
    // one mints it and succeeds, the other is refused for its own reason and rolls back — removing
    // the aid the successful one is now backed by, and leaving a shared collection with no app
    // identity. Under the lock the loser finds the aid already there, so `created` is false and
    // there is nothing for it to take back.
    //
    // The same key `manageSharedApp` serializes its operations on, deliberately: a deploy reads
    // the schemas, and running one half-way through a schema write is the interleaving both locks
    // exist to prevent. `updateManifest` keys on `manifest:` instead, so nothing here waits on
    // itself.
    const key = `operation:${await manifestKey(root)}`;
    return serializeBy(key, async () => {
      const ensured = await ensureAid(root);
      if (!ensured.ok) return noAppJson(ensured.problems);

      let narration: string;
      try {
        narration = await handler(args);
      } catch (err) {
        // A THROWN handler is a failed call too — the route turns it into "manageCollection
        // failed" — and it must not be the one path that keeps the mint. Rolled back and rethrown,
        // so the route's own error handling is unchanged.
        if (ensured.created) {
          await withdrawAid(root, ensured.aid);
        }
        throw err;
      }
      if (ensured.created && !wroteSchema(narration)) {
        await withdrawAid(root, ensured.aid);
      }
      return narration;
    });
  };
}

/** Take back an aid this call minted, and only that one.
 *
 *  Guarded on the value: between the mint and the failure, something else may have deployed the
 *  app — and an aid that is now the identity of a live `apps/{aid}` must not be removed because an
 *  unrelated schema write was refused. Best effort otherwise: the failure being reported is the
 *  engine's, and it is the one the agent needs. */
async function withdrawAid(root: string, minted: string): Promise<void> {
  await updateManifest(root, (manifest) => {
    if (manifest.aid !== minted) return null;
    // Rebuilt without the key rather than deleted from a copy: `no-dynamic-delete` aside, an
    // explicit filter says what this is — the declaration as the author left it.
    return Object.fromEntries(Object.entries(manifest).filter(([key]) => key !== "aid"));
  }).catch(() => ({ ok: false as const, problems: [] }));
}

function noAppJson(problems: readonly string[]): string {
  return [
    'This collection declares `storage.type: "firestore"`, which makes it a SHARED collection — its records live in an app\'s Firestore rather than in this repository.',
    "An app is a repository with an `app.json` at its root, and this step could not read one:",
    ...problems,
    'Write `app.json` first — `{ "members": { "<your address>": { "*": "owner" } } }` is enough, and the `aid` is generated here rather than chosen.',
  ].join("\n");
}
