// The single specification of what counts as harness-injected, iterated by BOTH specs that
// guard it — `userPromptText` (transcript) and `headerHookEffect` (live hook). Sharing the
// predicate is what makes the two agree; sharing this list is what holds each call site to
// it, so a path that stops consulting the predicate — an early return, a re-inlined copy —
// fails its own spec against shapes the other path still refuses. That is precisely what the
// hook path would have failed on before #1384, when only the transcript side knew about
// `<task-notification>`.
//
// Shapes are taken from real transcripts on disk, not invented.

export const INJECTED_PROMPTS: [name: string, text: string][] = [
  ["task-notification", "<task-notification>\n<task-id>boen82mbm</task-id>\n<tool-use-id>toolu_01Vv</tool-use-id>\n</task-notification>"],
  ["command-message", "<command-message>gh-review-loop</command-message>\n<command-name>/gh-review-loop</command-name>"],
  ["bash-input", "<bash-input>pwd</bash-input>"],
  ["local-command-caveat", "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>"],
  ["local-command-stdout", "<local-command-stdout>ok</local-command-stdout>"],
  ["system-reminder", "<system-reminder>\nThe user opened a new file.\n</system-reminder>"],
  // The anchor allows leading whitespace, so a block that arrives indented or after a blank
  // line is the same injection and must not slip through on formatting alone.
  ["leading newline", "\n  <task-notification>\n<task-id>abc</task-id>\n</task-notification>"],
];

// Prompts a person typed that happen to contain a marker. Nothing here may ever be refused —
// 591 real user lines mention `<task-notification` mid-sentence (the /loop skill's own
// documentation among them), and dropping those loses the prompt, not the injection.
export const NEAR_MISS_PROMPTS: [name: string, text: string][] = [
  ["mid-text mention", "what is a <task-notification> block?"],
  ["mid-text system-reminder", "why does <system-reminder> show up in the transcript?"],
  ["asks about the tag list", "add system-reminder to the injected list next to bash-input"],
  ["bare angle bracket", "<div> renders nothing"],
  ["unrelated leading tag", "<html> is not a harness block"],
];
